// Entity data extracted from ch_01.pdf
// Types: person, org, theme, instrument, document, era

window.GS_DATA = {
  eras: [
    { id: 'free_fall',   title: 'Free Fall',   start: 1968, end: 1994, blurb: 'Exponential arithmetic converted population dynamics into a moral emergency. The will to simplify.' },
    { id: 'quarantine',  title: 'Quarantine',  start: 1995, end: 2008, blurb: 'Immigration restriction survived delegitimation by embedding itself in the aesthetic of policy expertise. The rule of expertise.' },
    { id: 'swarm',       title: 'Swarm',       start: 2009, end: 2024, blurb: 'Decomposed demographic data became raw material for "great replacement" narratives. The politics of inevitability.' },
    { id: 'portfolio',   title: 'Portfolio',   start: 2025, end: 2048, blurb: 'Fertility rates as investment metrics; demography as asset class.' },
    { id: 'evacuation',  title: 'Evacuation',  start: 2049, end: 2068, blurb: 'Climate triage and selective rescue as administrative routine.' },
  ],

  people: [
    { id: 'olmsted_jr', name: 'Frederick Law Olmsted Jr.', role: 'Landscape architect', dates: '1870–1957', era: ['free_fall'],
      blurb: 'Authored the 1910 Boulder report; codified a grammar of scarcity and urgency that subordinated private property rights to a collectively defined vision of community character.',
      links: ['olmsted_report','chautauqua','blue_line','will_to_simplify'] },
    { id: 'bartlett', name: 'Albert Bartlett', role: 'Nuclear physicist · CU Boulder', dates: '1923–2013', era: ['free_fall','quarantine'],
      blurb: 'Manhattan Project alum who spent half a century translating exponential mathematics of radioactivity into a persuasive template about the consequences of growth. Co-instigator of the Blue Line.',
      links: ['mckelvey','plan_boulder','blue_line','exponential_curve','will_to_simplify','bartlett_lecture','cu_boulder','los_alamos'] },
    { id: 'mckelvey', name: 'Bob McKelvey', role: 'Mathematics · CU Boulder', dates: 'fl. 1958', era: ['free_fall'],
      blurb: 'In 1958 told Bartlett that something had to be done about the foothills. Co-instigator of PLAN-Boulder.',
      links: ['bartlett','plan_boulder','blue_line','cu_boulder'] },
    { id: 'porter', name: 'Theodore Porter', role: 'Historian of science', era: ['quarantine','swarm'],
      blurb: 'Diagnosed quantification as a "technology of trust": numerical objectivity spreads not by accuracy but by supplying a politically useful pose of impersonality.',
      links: ['rule_of_expertise','quant_chauvinism'] },
    { id: 'desrosieres', name: 'Alain Desrosières', role: 'Sociologist of statistics', era: ['quarantine'],
      blurb: 'Showed that statistical categories are political settlements naturalized through institutional routinization.',
      links: ['rule_of_expertise','quant_chauvinism'] },
    { id: 'arendt', name: 'Hannah Arendt', role: 'Political theorist', dates: '1906–1975',
      blurb: 'Defined chauvinism as the conversion of asserted superiority into self-evident premise of political judgment. Race-thinking and the camp as political technology.',
      links: ['quant_chauvinism','ecofascist_imaginary'] },
    { id: 'griffin', name: 'Roger Griffin', role: 'Fascism theorist',
      blurb: 'Defined fascism as palingenetic ultranationalism — the myth of national rebirth from decadence — distinguishing ecofascism from adjacent forms.',
      links: ['ecofascist_imaginary','palingenesis'] },
    { id: 'jasanoff', name: 'Sheila Jasanoff', role: 'STS scholar',
      blurb: 'Sociotechnical imaginaries: collectively held visions stabilized through laws, infrastructures, and routines that enact futures rather than merely describe them.',
      links: ['ecofascist_imaginary','quant_chauvinism'] },
    { id: 'connelly', name: 'Matthew Connelly', role: 'Historian', era: ['free_fall'],
      blurb: 'Showed how mid-century demographic science was recruited into a coercive apparatus targeting the fertility of women in the Global South.',
      links: ['population_bomb','quant_chauvinism'] },
    { id: 'merchant', name: 'Emily Klancher Merchant', role: 'Historian of demography',
      blurb: 'Reconstructed how "the population bomb" was assembled as a scientific and policy object.',
      links: ['population_bomb'] },
    { id: 'hartmann', name: 'Betsy Hartmann', role: 'Feminist scholar',
      blurb: 'Population control as global governance project that subordinated women\u2019s reproductive autonomy to demographic targets.',
      links: ['population_bomb'] },
    { id: 'tanton', name: 'John Tanton (network)', role: 'Anti-immigration network', era: ['quarantine','swarm'],
      blurb: 'Network whose impact statements hierarchized immigrant populations by fiscal burden.',
      links: ['fiscal_impact','rule_of_expertise'] },
  ],

  orgs: [
    { id: 'plan_boulder', name: 'PLAN-Boulder', full: "People's League for Action Now", founded: 1959, era: ['free_fall'],
      blurb: 'Citizen coalition that successfully campaigned for the Blue Line Amendment.',
      links: ['bartlett','mckelvey','blue_line','open_space_program','danish_plan'] },
    { id: 'olmsted_brothers', name: 'Olmsted Brothers', full: 'Brookline, MA landscape architecture firm', era: ['free_fall'],
      blurb: 'Retained by Boulder City Improvement Association in 1908. Authored the 1910 report.',
      links: ['olmsted_jr','olmsted_report','bcia'] },
    { id: 'bcia', name: 'Boulder City Improvement Assn.', founded: 1908, era: ['free_fall'],
      blurb: 'Civic body that retained Olmsted Brothers to survey Boulder and recommend improvements.',
      links: ['olmsted_brothers','olmsted_report'] },
    { id: 'chautauqua', name: 'Colorado Chautauqua', founded: 1898, era: ['free_fall'],
      blurb: 'Bounded and selective community on public land. Built in physical form the social logic the Olmsted report would extend.',
      links: ['olmsted_jr','olmsted_report'] },
    { id: 'cu_boulder', name: 'CU Boulder', full: 'University of Colorado, Boulder', founded: 1876, era: ['free_fall','quarantine'],
      blurb: 'Land-grant university charged with transforming Colorado\u2019s miners and farmers into good American citizens.',
      links: ['bartlett','mckelvey'] },
    { id: 'los_alamos', name: 'Los Alamos / Manhattan Project', era: ['free_fall'],
      blurb: 'Where Bartlett spent the final years of WWII measuring plutonium isotopes.',
      links: ['bartlett'] },
    { id: 'sierra_club', name: 'Sierra Club', era: ['free_fall','quarantine'],
      blurb: 'Newsletters carried Bartlett\u2019s exponential curve into broader circulation.',
      links: ['bartlett','exponential_curve'] },
    { id: 'census_bureau', name: 'U.S. Census Bureau', era: ['swarm'],
      blurb: 'Released the 2008 majority-minority projection that supplied visual grammar for replacement narratives.',
      links: ['majority_minority','politics_of_inevitability'] },
    { id: 'cis', name: 'Center for Immigration Studies (CIS)', era: ['quarantine','swarm'],
      blurb: 'Tanton-network think tank circulating fiscal impact statements as policy expertise.',
      links: ['tanton','fiscal_impact'] },
  ],

  themes: [
    { id: 'quant_chauvinism', name: 'Quantitative Chauvinism', kind: 'theme',
      blurb: 'The deployment of numerical instruments to foreclose political deliberation by converting contested claims into apparent technical necessities.',
      links: ['will_to_simplify','rule_of_expertise','politics_of_inevitability','porter','desrosieres','arendt'] },
    { id: 'ecofascist_imaginary', name: 'Eco-fascist Imaginary', kind: 'theme',
      blurb: 'Organized visions of environmental futures that naturalize hierarchy and exclusion as ecological necessity.',
      links: ['palingenesis','jasanoff','griffin','arendt'] },
    { id: 'will_to_simplify', name: 'Will to Simplify', kind: 'theme',
      blurb: 'Compression of complex demographic and ecological processes into a single governing metric.',
      links: ['exponential_curve','bartlett','quant_chauvinism','free_fall'] },
    { id: 'rule_of_expertise', name: 'Rule of Expertise', kind: 'theme',
      blurb: 'Insulation of quantified claims from democratic scrutiny through credentialed authority.',
      links: ['fiscal_impact','tanton','porter','quant_chauvinism','quarantine'] },
    { id: 'politics_of_inevitability', name: 'Politics of Inevitability', kind: 'theme',
      blurb: 'Conversion of conditional projections into mandates that foreclose political choice.',
      links: ['majority_minority','census_bureau','quant_chauvinism','swarm'] },
    { id: 'palingenesis', name: 'Palingenesis', kind: 'theme',
      blurb: 'Myth of national rebirth from decadence \u2014 the structure that distinguishes fascism from adjacent forms.',
      links: ['griffin','ecofascist_imaginary'] },
    { id: 'carrying_capacity', name: 'Carrying Capacity', kind: 'instrument',
      blurb: 'A bounded endowment, a threat of irreversible loss, expert authority translating threat into urgency.',
      links: ['danish_plan','bvcp','will_to_simplify'] },
    { id: 'population_bomb', name: 'The Population Bomb', kind: 'theme',
      blurb: 'Crisis narrative assembled by demographers, ecologists, and foundation officers from uncertain projections.',
      links: ['merchant','connelly','hartmann','exponential_curve'] },
  ],

  instruments: [
    { id: 'blue_line', name: 'Blue Line Amendment', kind: 'instrument', year: 1959, era: ['free_fall'],
      blurb: 'Prohibited the city from extending water service above a fixed elevation contour, making hillside development administratively impossible.',
      links: ['plan_boulder','bartlett','mckelvey','olmsted_report'] },
    { id: 'open_space_program', name: 'Open Space Program', kind: 'instrument', year: 1967, era: ['free_fall'],
      blurb: 'Authorized the city to purchase and permanently retire land on its mountain and plains perimeter.',
      links: ['plan_boulder','blue_line'] },
    { id: 'danish_plan', name: 'Danish Plan', kind: 'instrument', year: 1976, era: ['free_fall'],
      blurb: 'Capped annual residential building permits at 450 units, derived from infrastructure and carrying-capacity calculations.',
      links: ['carrying_capacity','plan_boulder'] },
    { id: 'bvcp', name: 'Boulder Valley Comprehensive Plan', kind: 'instrument', year: 1977, era: ['free_fall'],
      blurb: 'Formalized a population ceiling for the planning area; translated intuition about proper scale into administrative target.',
      links: ['carrying_capacity','danish_plan'] },
    { id: 'exponential_curve', name: 'The Exponential Curve', kind: 'instrument', era: ['free_fall','quarantine'],
      blurb: 'Bartlett\u2019s portable doubling-time thought experiment. Compresses fertility, mortality, migration, technology, consumption, distribution into a single alarming metric.',
      links: ['bartlett','will_to_simplify','population_bomb','sierra_club'] },
    { id: 'fiscal_impact', name: 'Fiscal Impact Statement', kind: 'instrument', era: ['quarantine'],
      blurb: 'Per-household burden calculation that converts a political claim ("certain people cost too much") into an administrative finding.',
      links: ['cis','tanton','rule_of_expertise'] },
    { id: 'majority_minority', name: 'Majority-Minority Projection', kind: 'instrument', year: 2008, era: ['swarm'],
      blurb: 'Census Bureau projection showing non-Hispanic whites becoming a minority by 2042. Conditional projection rendered as countdown.',
      links: ['census_bureau','politics_of_inevitability'] },
  ],

  documents: [
    { id: 'olmsted_report', name: 'Improvement of Boulder, Colorado', kind: 'document', year: 1910, author: 'Olmsted Jr.',
      blurb: 'A genuinely reformist work that is also one of the earliest codifications of a vision of environmental preservation specifying who belongs.',
      excerpt: 'The Cost of Delay recurs through the report like a drumbeat, marking each moment where inaction is characterized not as a value-neutral choice but as responsible stewardship deferred at collective expense.',
      pages: 'p. 65',
      links: ['olmsted_jr','olmsted_brothers','bcia','blue_line','will_to_simplify','chautauqua'] },
    { id: 'bartlett_lecture', name: '"Arithmetic, Population & Energy"', kind: 'document', year: 1976, author: 'Bartlett',
      blurb: 'The bottle, the bacterium, the doubling time. Pedagogically brilliant; politically consequential.',
      excerpt: '"At what time was the bottle half full?" Bartlett asks. The audience hesitates. "Eleven fifty-nine," he says. "One minute before noon."',
      pages: 'Bartlett (1976)',
      links: ['bartlett','exponential_curve','will_to_simplify','population_bomb'] },
    { id: 'blue_line_amendment_doc', name: 'Blue Line Amendment (text)', kind: 'document', year: 1959,
      blurb: 'Charter provision prohibiting water service above a fixed elevation.',
      excerpt: 'The city needed only to define a line on a map to achieve its policy goal.',
      links: ['blue_line','plan_boulder','bartlett','mckelvey'] },
    { id: 'danish_plan_doc', name: 'Danish Plan (ordinance)', kind: 'document', year: 1976,
      blurb: '450-unit cap, derived from "calculations about infrastructure capacity and environmental carrying capacity that arrived at the city council bearing the authority of technical necessity."',
      links: ['danish_plan','carrying_capacity'] },
    { id: 'census_2008_proj', name: '2008 Census Projection', kind: 'document', year: 2008,
      blurb: 'Crossover chart with converging lines and marked intersection point — the visual grammar of a countdown.',
      links: ['majority_minority','census_bureau','politics_of_inevitability'] },
  ],
};

// Build lookup
(function(){
  const D = window.GS_DATA;
  const all = [
    ...D.people.map(x => ({ ...x, kind: 'person' })),
    ...D.orgs.map(x => ({ ...x, kind: 'org' })),
    ...D.themes.map(x => ({ ...x, kind: x.kind || 'theme' })),
    ...D.instruments.map(x => ({ ...x, kind: 'instrument' })),
    ...D.documents.map(x => ({ ...x, kind: 'document' })),
    ...D.eras.map(x => ({ ...x, kind: 'era', name: x.title })),
  ];
  D.byId = Object.fromEntries(all.map(x => [x.id, x]));
  D.all = all;
})();
