// Build the TypeScript islands bundle.
// Input:  assets/js/islands/index.ts (the entry; mounts everything)
// Output: assets/js/dist/islands.js (single IIFE bundle, committed to git)
//
// The bundle is committed because GitHub Pages builds with the github-pages
// gem and never runs npm — Pages only sees the static JS files in the repo.
// Run `npm run build` locally before committing changes to assets/js/islands/**.
//
// React + ReactDOM are bundled in (not externalized) so this file is fully
// self-contained. The bundle augments globalThis with window.ScrollyNetwork
// (replacing the legacy assets/js/scrolly-network.jsx) and auto-mounts any
// `[data-island]` element on DOMContentLoaded. See assets/js/islands/index.ts.

import * as esbuild from 'esbuild';

const watch = process.argv.includes('--watch');

/** @type {import('esbuild').BuildOptions} */
const config = {
  entryPoints: ['assets/js/islands/index.ts'],
  bundle: true,
  outfile: 'assets/js/dist/islands.js',
  platform: 'browser',
  format: 'iife',
  target: ['es2020'],
  jsx: 'automatic',
  jsxImportSource: 'react',
  minify: !watch,
  sourcemap: watch ? 'inline' : true,
  loader: { '.json': 'json' },
  define: {
    'process.env.NODE_ENV': watch ? '"development"' : '"production"',
  },
  banner: {
    js: '/* The Greatest Shortcoming — islands bundle. Generated by esbuild from assets/js/islands/. Do not edit by hand; edit the TypeScript source and run `npm run build`. */',
  },
  metafile: true,
  logLevel: 'info',
};

if (watch) {
  const ctx = await esbuild.context(config);
  await ctx.watch();
  console.log('esbuild: watching assets/js/islands/ for changes...');
} else {
  const result = await esbuild.build(config);
  const outputs = Object.entries(result.metafile?.outputs ?? {});
  for (const [path, info] of outputs) {
    const kb = (info.bytes / 1024).toFixed(1);
    console.log(`  ${path}  (${kb} KB)`);
  }
}
