// Build the TypeScript islands bundle.
// Input:  assets/js/islands/index.ts (the entry; mounts everything)
// Output: assets/js/dist/islands.js (single IIFE bundle, committed to git)
//
// The bundle is committed because GitHub Pages builds with the github-pages
// gem and never runs npm — Pages only sees the static JS files in the repo.
// Run `npm run build` locally before committing changes to assets/js/islands/**.
//
// React + ReactDOM are EXTERNALIZED to the global window.React /
// window.ReactDOM that _layouts/scrolly.html already loads from CDN for
// app.jsx. Bundling our own copy of React produces two React instances on
// the page; when app.jsx renders <window.ScrollyNetwork ...> inline, the
// component is instantiated by CDN React's renderer but its hooks call
// into bundled React's dispatcher, which is null because no render is in
// progress on its instance ("can't access property 'useMemo', Ft.current
// is null"). Externalizing to the same global instance fixes the bug and
// also drops the bundle from ~460 KB to ~150 KB.
//
// JSX uses the classic transform (jsx: 'transform' + jsxFactory:
// 'React.createElement') rather than the automatic runtime so we avoid
// importing 'react/jsx-runtime' (which would also need a global mapping).
// The free `React` identifier in compiled JSX is then rewritten to
// `window.React` via esbuild's `define` option.

import * as esbuild from 'esbuild';

const watch = process.argv.includes('--watch');

// Modules to alias to globals at runtime. Map key = bare-import specifier;
// value = JS expression evaluated at runtime to produce the module object.
const externalGlobals = {
  react: 'window.React',
  'react-dom': 'window.ReactDOM',
  'react-dom/client': 'window.ReactDOM',
};

/** @type {import('esbuild').Plugin} */
const externalGlobalsPlugin = {
  name: 'external-globals',
  setup(build) {
    const names = new Set(Object.keys(externalGlobals));
    build.onResolve({ filter: /.*/ }, (args) => {
      if (names.has(args.path)) {
        return { path: args.path, namespace: 'external-global' };
      }
      return null;
    });
    build.onLoad({ filter: /.*/, namespace: 'external-global' }, (args) => ({
      // CommonJS-style module so both `import X from 'react'` and
      // `import { useMemo } from 'react'` resolve correctly to the global.
      contents: `module.exports = ${externalGlobals[args.path]};`,
      loader: 'js',
    }));
  },
};

/** @type {import('esbuild').BuildOptions} */
const config = {
  entryPoints: ['assets/js/islands/index.ts'],
  bundle: true,
  outfile: 'assets/js/dist/islands.js',
  platform: 'browser',
  format: 'iife',
  target: ['es2020'],
  jsx: 'transform',
  jsxFactory: 'React.createElement',
  jsxFragment: 'React.Fragment',
  minify: !watch,
  sourcemap: watch ? 'inline' : true,
  loader: { '.json': 'json' },
  define: {
    // Free `React` identifier produced by JSX compilation → window.React.
    React: 'window.React',
    'process.env.NODE_ENV': watch ? '"development"' : '"production"',
  },
  banner: {
    js: '/* The Greatest Shortcoming — islands bundle. Generated by esbuild from assets/js/islands/. Do not edit by hand; edit the TypeScript source and run `npm run build`. */',
  },
  plugins: [externalGlobalsPlugin],
  metafile: true,
  logLevel: 'info',
};

if (watch) {
  const ctx = await esbuild.context(config);
  await ctx.watch();
  console.log('esbuild: watching assets/js/islands/ for changes...');
} else {
  const result = await esbuild.build(config);
  const outputs = Object.entries(result.metafile?.outputs ?? {});
  for (const [path, info] of outputs) {
    const kb = (info.bytes / 1024).toFixed(1);
    console.log(`  ${path}  (${kb} KB)`);
  }
}
